### ISSUE TITLE
[Feature] Clearance Request/Issue Time

### ISSUE THREAD

**Issue by Phil061995** [vACDM/vacdm-plugin-v1#39]
New times to track and sync the clearance request and issue time. No real ACDM times but helpfull on Vatsim, especially during high traffic situations and controller changes.

**New TagItems:**
- ACRT (Actual Clearance Request Time)
- ACIT (Actual Clearance Issue Time)

Colors should be like ASRT and ASAT. ACRT grey when ACIT available.

**New TagFunctions:**
- set ACRT
- set ACIT + ACRT (if not set) + Clearance Received Flag (setting the CRF should also work when slave only that this function can always be used to set the CRF even if not using vACDM)
- set ACIT + ACRT (if not set)
- reset ACRT
- reset ACIT
- add reset to the reset menu

**Problem:**
Clearances issued via datalink. Additional click required to set the ACIT. 

We can not trust in the CRF due to sync problems and everyone is able to set it and could trigger the ACIT. Also new flights that were inbound flights before without disconnect keep their status as well as the CRF and could cause problems.

**Comment by LeoKle** [comment]
Please move the feature request into [#feature-requests](https://discord.com/channels/802213274443579462/1224687387800768584), so we can discuss it here
